SELECT 
    ID_EMPRESA AS 'CÓD. EMPRESA',
    CD_FUNCIONARIO AS 'CÓD. FUNC.',
    DS_NOME AS 'NOME',
    DT_DEMISSAO AS 'DATA DEMISSAO'
FROM
    CAD_FUNCIONARIO
WHERE
    DT_DEMISSAO IS NULL
ORDER BY ID_EMPRESA ASC , CD_FUNCIONARIO DESC;