SELECT 
    ID_EMPRESA, CD_FUNCIONARIO, DS_NOME
FROM
    CAD_FUNCIONARIO
WHERE
    CD_FUNCIONARIO >= 50
        AND CD_FUNCIONARIO <= 100;
        
SELECT 
    ID_EMPRESA, CD_FUNCIONARIO, DS_NOME
FROM
    CAD_FUNCIONARIO
WHERE
    CD_FUNCIONARIO BETWEEN 50 AND 100
ORDER BY DS_NOME;        